CREATE DATABASE lancamentos;

CREATE TABLE lancamento (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descricao" varchar,
  "data_lancamento" date,
  "valor" decimal,
  "tipo_lancamento" varchar,
  "situacao" varchar,
  "id_usuario" integer
);

CREATE TABLE usuario (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "login" varchar,
  "senha" varchar,
  "situacao" varchar
);

ALTER TABLE lancamento ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;


INSERT INTO usuario (nome, login, senha, situacao) VALUES ('Daniel', 'daniel', MD5('123456'), 'ativo');
INSERT INTO usuario (nome, login, senha, situacao) VALUES ('Maria', 'maria', MD5('123456'), 'ativo');
INSERT INTO usuario (nome, login, senha, situacao) VALUES ('Pedro', 'pedro', MD5('123456'), 'ativo');


INSERT INTO lancamento (descricao, data_lancamento, valor, tipo_lancamento, situacao, id_usuario) VALUES
('Salário', '2024-03-01', 5000.00, 'RECEITA', 'EFETIVADO', 1),
('Aluguel', '2024-03-05', 1200.00, 'DESPESA', 'EFETIVADO', 1),
('Freelance desenvolvimento', '2024-03-08', 1500.00, 'RECEITA', 'PENDENTE', 2),
('Conta de luz', '2024-03-10', 180.50, 'DESPESA', 'EFETIVADO', 2),
('Supermercado', '2024-03-12', 450.75, 'DESPESA', 'EFETIVADO', 1),
('Consultoria', '2024-03-15', 3000.00, 'RECEITA', 'PENDENTE', 3),
('Internet', '2024-03-15', 99.90, 'DESPESA', 'EFETIVADO', 3),
('Venda de equipamento', '2024-03-18', 800.00, 'RECEITA', 'EFETIVADO', 2),
('Plano de saúde', '2024-03-20', 320.00, 'DESPESA', 'PENDENTE', 1),
('Dividendos', '2024-03-25', 2200.00, 'RECEITA', 'EFETIVADO', 3);