name: Pipeline Homologação

on:
  workflow_dispatch:

jobs:
  qualidade-codigo:
    uses: ./.github/workflows/pylint.yml

  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          pip install -r requirements-dev.txt
          pip install pytest-cov # Garante que o gerador de cobertura esteja presente

      - name: Executar Testes e gerar XML
        run: |
          pytest --junitxml=result.xml --cov=app --cov-report=term-missing

      - name: Exibir estatísticas no PR
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() # Roda mesmo se os testes falharem para mostrar o que errou
        with:
          files: result.xml

  deploy-homolog:
    needs: [qualidade-codigo, testes] 
    runs-on: self-hosted
    steps:
      - name: Atualização do ambiente de Homologação
        run: |
          # Entra na pasta criada no provisionamento
          cd /home/univates/CM/homolog
          
          if [ -d ".git" ]; then
            echo "Repositório detectado. Sincronizando com a branch homolog..."
            # Baixa as atualizações do GitHub sem tentar mesclar ainda
            git fetch origin homolog
            # Força a pasta da VM a ficar EXATAMENTE igual à branch do GitHub, ignorando mudanças locais
            git reset --hard origin/homolog
          else
            echo "Clonando pela primeira vez..."
            # Usar o GITHUB_TOKEN nativo evita que você precise criar e manter um Personal Access Token
            # git clone -b homolog https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
            git clone -b homolog https://github.com/DanielCorbellini/task2-configurationManagment.git
          fi
          
          echo "Subindo os containers do ambiente de Homologação..."
          # Se o usuário não estiver no grupo docker, coloque "sudo docker compose" aqui
          docker compose up -d --build
