name: Pipeline Produção

on:
  workflow_dispatch:

jobs:
  qualidade-codigo:
    uses: ./.github/workflows/pylint.yml

  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          pip install -r requirements-dev.txt
          pip install pytest-cov

      - name: D) Executar Testes em ambiente de Produção
        run: |
          pytest --junitxml=result.xml --cov=app --cov-report=term-missing

      - name: Exibir estatísticas
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: result.xml

  deploy-producao:
    needs: [qualidade-codigo, testes] 
    runs-on: ubuntu-latest
    steps:
      - name: Atualização do ambiente de Produção
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASS }}
          script: |
            cd /home/univates/CM/prod
            
            if [ -d ".git" ]; then
              echo "Atualizando ambiente de produção..."

              git fetch origin
              git switch main
              git pull origin main
            else
              echo "Clonando produção pela primeira vez..."
              git clone -b main https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git .
            fi
            
            # Atualiza os containers de produção
            # Mudar a porta depois
            docker compose up -d --build
