name: Configurar VM zerada 2

on:
  workflow_dispatch:

jobs:
  setup-infraestrutura:
    runs-on: self-hosted

    steps:
      - name: Instalar dependências e configurar pastas
        run: |
          set -x
          
          echo "Atualizando lista de pacotes e instalando uidmap (necessário para Docker rootless)..."
          # A flag DEBIAN_FRONTEND=noninteractive previne que o apt-get trave pedindo confirmações visuais
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y uidmap

          echo "Instalando o Docker..."
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

          echo "Instalando o plugin do Docker Compose..."
          sudo apt-get install docker-compose-plugin -y

          echo "Configurando o Docker Rootless..."
          # Desabilita o Docker root padrão para evitar conflitos na porta/socket
          sudo systemctl disable --now docker.service docker.socket
          
          # Instala a versão rootless para o usuário atual do runner
          dockerd-rootless-setuptool.sh install

          echo "Criando pastas dos ambientes HOMOLOG e PROD..."
          mkdir -p /home/univates/CM/homolog
          mkdir -p /home/univates/CM/prod

          echo "Ajustando as permissões das pastas..."
          sudo chown -R $USER:$USER /home/univates/CM/homolog
          sudo chown -R $USER:$USER /home/univates/CM/prod

          echo "Provisionamento concluído! A VM está pronta para receber os ambientes!"
