name: Configurar VM zerada

on:
  workflow_dispatch:

jobs:
  setup-infraestrutura:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar na VM e instalar dependências
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          passphrase: ${{ secrets.VM_PASSPHRASE }}
          sync: true
          debug: true
          script: |
            echo "teste"
            sudo apt-get update -y

            sudo mkdir -p /home/univates/CM/homolog
            sudo mkdif -p /home/univates/CM/prod

            echo "Ajustando as permissões das pastas..."
            sudo chown -R $USER:$USER /opt/app
            
